### ISSUE TITLE
UI - no content

### ISSUE THREAD

**Issue by shift18** [jocmp/capyreader#1392]
### Steps to Reproduce

1. Open app
2. No content

### Expected behavior

Content when app is open
Content will return if you scroll

### Screenshots or screen recording

<img src="https://github.com/user-attachments/assets/c963accc-550e-423b-ba10-a991c5e6ba14" width="200">

### Device, Operating system, and app version

GOS: Android 16, build 2025080600
Phone Bluejay

Sry about being brief, device out of RAM so my input keeps disappearing

**Comment by jocmp** [comment]
Hey @shift18, thanks for the report. Can you share your crash logs for this just in case its a database issue?

Just two other ideas: is the memory issue a persistent problem? That could contribute to the placeholder problem. Additionally, what your refresh interval set to? (On Start, Manually, 15m, etc)

**Comment by shift18** [comment]
> Hey [@shift18](https://github.com/shift18), thanks for the report. Can you share your crash logs for this just in case its a database issue?
> 
> Just two other ideas: is the memory issue a persistent problem? That could contribute to the placeholder problem. Additionally, what your refresh interval set to? (On Start, Manually, 15m, etc)

### Memory issue?
Not really, most of time its fine unless i multitask and one of the apps is heavy like my navigator app.

**Refresh interval** 30 min
**App version** 2025.08.1153
**Feed source** locally fetched

**Logs** check your inbox

**Comment by Soulsuke** [comment]
If it can help... It happens to me at the start of each refresh. Content then comes back either sometimes after it finished fetching (not always though) or consistently changing feed (eg. all -> feed works, going back to all then shows everything correctly).

Started happening since the last update on f-droid

**Comment by jocmp** [comment]
Thanks @Soulsuke. It seems like the issue lines time-wise for both you and @shift18. I believe this may have been a bad side effect of some list changes I made a few weeks back.

I pushed a change in [2025.08.1157-dev](https://github.com/jocmp/capyreader/releases/tag/2025.08.1157-dev). Let me know if that fixes it if you download it. I also started pushing a separate APK called "Capy Nightly" in case you want to try out the fix without updating the main app:

- https://github.com/jocmp/capyreader/releases/tag/2025.08.21-nightly

**Comment by Soulsuke** [comment]
Thanks @jocmp , the issue seems resolved in the nightly apk

**Comment by shift18** [comment]
> Thanks [@Soulsuke](https://github.com/Soulsuke). It seems like the issue lines time-wise for both you and [@shift18](https://github.com/shift18). I believe this may have been a bad side effect of some list changes I made a few weeks back.
> 
> I pushed a change in [2025.08.1157-dev](https://github.com/jocmp/capyreader/releases/tag/2025.08.1157-dev). Let me know if that fixes it if you download it. I also started pushing a separate APK called "Capy Nightly" in case you want to try out the fix without updating the main app:
> 
> * https://github.com/jocmp/capyreader/releases/tag/2025.08.21-nightly

The issue already seems to have been resolved with build [25.08.1156](https://github.com/jocmp/capyreader/releases/tag/2025.08.1156)

I guess **"Only refresh on start when "On Start" is selected"**(https://github.com/jocmp/capyreader/pull/1403) fixed or at least mitigated effects of this issue

Thanks for putting time into this @jocmp

**Comment by jocmp** [comment]
Aha, good to know! In that case I'll revert my most recent change back to the version in build 1156. That should also hit F-Droid soon. Currently F-Droid is still pointing to 1153.

**Comment by shift18** [comment]
> Aha, good to know! In that case I'll revert my most recent change back to the version in build 1156. That should also hit F-Droid soon. Currently F-Droid is still pointing to 1153.

Yeah okay, if the issue reemerges I'll be sure post about it here

**Comment by shift18** [comment]
> > Aha, good to know! In that case I'll revert my most recent change back to the version in build 1156. That should also hit F-Droid soon. Currently F-Droid is still pointing to 1153.
> 
> Yeah okay, if the issue reemerges I'll be sure post about it here

I spoke to soon, the issue is back.
I Guess the 1156 update just mitigated the issue.
I'll send you the logs just as before

**Comment by Soulsuke** [comment]
@jocmp Just pulled 2025.08.1156 from F-Droid and it fixed the issue for me

**Comment by jocmp** [comment]
Thanks @Soulsuke. @shift18 was still experiencing issues with that release, so I'm skeptical if it actually works in all cases.

I also think this may be related to another list issue - https://github.com/jocmp/capyreader/issues/1419. I'm reverting some changes back to the way it was in [2025.07.1148](https://github.com/jocmp/capyreader/releases/tag/2025.07.1148) which was released in July to be doubly sure.

**Comment by jocmp** [comment]
Closing for now that build 1164 is live. Please let me know if you're still seeing these issues!
